### ISSUE TITLE
List for V1.1

### ISSUE THREAD

**Issue by Salbei2500** [gruppe-adler/TvT_HoldingPoint.Altis#2]
- [x] Improve Balancing
- [x] Improve Visuals on Map
- [x] add Clothing to Buymenu
- [x] integreat armorBar to show that it is awsome! https://github.com/gruppe-adler/grad_armorBar

**Comment by Fusselwurm** [comment]
one more thing to suggest: slot ordering. yesterday, there were more officers than regular soldiers – because they get more money. *if* you want to give TLs more money than regular soldiers, the slotting screen *should* be sorted in such a way that the game is balanced, if players of both sides select a consecutive list of slots, starting at the top (that is, leave no holes/open slots among the filled slots in the slot list)

**Comment by Salbei2500** [comment]
Yeah, i Removed extra money for TL's so no more of that 😄

**Comment by Salbei2500** [comment]
Done
